version: "3"
services:
  golang:
    container_name: "golang"
    build: ./docker/go
    restart: always
    volumes:
      - ./:/app
    ports:
      - "8080:3000"
    depends_on:
      - mysql
  mysql:
    container_name: "mysql"
    build: ./docker/mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql:delegated
    environment:
      - MYSQL_DATABASE=go_clean_architecture_web_application_boilerplate
      - MYSQL_ROOT_PASSWORD=password
volumes:
  mysql_db:
    driver: local