FROM golang:1.17-buster 

RUN apt update && apt install git \
    binutils-gold \
    curl \
    g++ \
    gcc \
    gnupg \
    make

RUN mkdir /app

COPY ../../ /tmp

RUN ls -al /tmp

COPY ./air-install.sh /tmp/install.sh

RUN chmod +x /tmp/install.sh

RUN bash /tmp/install.sh

RUN go install github.com/directoryxx/fiber-clean-template/cmd

# RUN go get github.com/oxequa/realize
WORKDIR /app



CMD ["air"]